plugins {
    id 'com.android.application'
}

android {
    namespace 'it.mrf2024.ekoclienti'
    compileSdk 35

    defaultConfig {
        applicationId 'it.mrf2024.ekoclienti'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0-test'
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }
}
